In [1]:
import numpy as np
import pandas as pd

In [5]:
hea_16 = pd.read_stata('ch16i_EN_1.0p.dta')
rel_16 = pd.read_stata('cr16i_1.0p_EN.dta')
soc_16 = pd.read_stata('cs16i_EN_1.0p.dta')
fam_16 = pd.read_stata('cf16i_EN_1.0p.dta')
wor_16 = pd.read_stata('cw16i_EN_2.0p.dta')
per_16 = pd.read_stata('cp17i_EN_1.0p.dta')
val_16 = pd.read_stata('cv16h_EN_1.0p.dta')
ass_16 = pd.read_stata('ca16e_EN_1.0p.dta')
inc_16 = pd.read_stata('ci16i_EN_3.0p.dta')
hou_16 = pd.read_stata('cd16i_EN_1.0p.dta')

# no 2016 for personality

In [3]:
all_16 = [ass_16, hou_16, fam_16, hea_16, inc_16, per_16, soc_16, val_16, wor_16]

merged_16 = all_16[0]

for all in all_16[1:]:
    merged_16 = pd.merge(merged_16, all, on='nomem_encr', how='inner')

In [4]:
merged_16.head()

,nomem_encr,ca16e_m,ca16e001,ca16e002,ca16e003,ca16e082,ca16e078,ca16e005,ca16e006,ca16e007,...,cw16i496,cw16i497,cw16i498,cw16i499,cw16i500,cw16i501,cw16i502,cw16i503,cw16i504,cw16i505
0,800015.0,201607.0,yes,yes,head of household*,53.0,yes,no,no,no,...,1 = certainly not,5 = certainly yes,1 = certainly not,2,1 = certainly not,09-04-2016,15:53:02,09-04-2016,16:40:04,2822.0
1,800054.0,201607.0,no,yes,head of household*,69.0,yes,no,no,no,...,1 = certainly not,5 = certainly yes,3,3,3,05-04-2016,11:53:49,05-04-2016,12:02:56,547.0
2,800057.0,201607.0,no,no,unmarried partner,41.0,yes,no,no,no,...,3,3,3,3,1 = certainly not,04-04-2016,14:13:30,04-04-2016,14:24:42,672.0
3,800170.0,201607.0,no,yes,head of household*,57.0,yes,no,no,no,...,1 = certainly not,5 = certainly yes,4,5 = certainly yes,5 = certainly yes,05-04-2016,17:25:35,05-04-2016,17:46:25,1250.0
4,800186.0,201607.0,no,yes,head of household*,77.0,yes,no,no,no,...,1 = certainly not,4,4,4,5 = certainly yes,06-04-2016,14:14:16,06-04-2016,14:24:32,616.0