In [1]:
import numpy as np
import pandas as pd

In [6]:
ass_08 = pd.read_stata('ca08a_1.0p_EN/ca08a_1.0p_EN.dta')
ass_10 = pd.read_stata('ca10b_EN_1.0p/ca10b_EN_1.0p.dta')
ass_12 = pd.read_stata('ca12c_EN_1.0p/ca12c_EN_1.0p.dta')
ass_14 = pd.read_stata('ca14d_2.0p_EN/ca14d_2.0p_EN.dta')
ass_16 = pd.read_stata('ca16e_EN_1.0p/ca16e_EN_1.0p.dta')
ass_18 = pd.read_stata('ca18f_EN_1.0p/ca18f_EN_1.0p.dta')
ass_20 = pd.read_stata('ca20g_EN_1.0p/ca20g_EN_1.0p.dta')
ass_22 = pd.read_csv('ca22h_EN_1.0p/ca22h_EN_1.0p.csv')

In [7]:
ass_20.head()

,nomem_encr,ca20g_m,ca20g001,ca20g002,ca20g003,ca20g082,ca20g078,ca20g005,ca20g006,ca20g007,...,ca20g066,ca20g067,ca20g068,ca20g069,ca20g070,ca20g071,ca20g072,ca20g073,ca20g074,ca20g075
0,800009.0,202009.0,yes,no,head of household*,65.0,yes,yes,no,no,...,certainly not,certainly yes,certainly not,2,4,21-09-2020,22:14:13,21-09-2020,22:15:56,103.0
1,800015.0,202009.0,yes,yes,head of household*,57.0,yes,no,no,no,...,certainly not,certainly yes,certainly not,certainly not,certainly not,11-09-2020,09:16:15,11-09-2020,09:19:37,202.0
2,800057.0,202009.0,yes,no,unmarried partner,45.0,yes,no,yes,no,...,4,3,2,certainly not,certainly not,28-09-2020,12:17:20,28-09-2020,12:23:16,356.0
3,800058.0,202009.0,no,yes,head of household*,22.0,yes,no,no,no,...,certainly yes,certainly yes,3,3,2,08-09-2020,11:00:33,08-09-2020,11:59:31,3538.0
4,800100.0,202009.0,yes,no,married partner,29.0,yes,no,no,no,...,certainly not,certainly yes,certainly yes,certainly yes,certainly yes,19-09-2020,20:27:19,19-09-2020,20:30:13,174.0

In [ ]:
ass_merged = pd.merge(ass_08, ass_10, ass_12, ass_14, ass_16, ass_18, ass_20, ass_22, on='nomem_encr', how='' )