In [1]:
import numpy as np
import pandas as pd

In [20]:
ass_08 = pd.read_stata('ca08a_1.0p_EN/ca08a_1.0p_EN.dta')
ass_10 = pd.read_stata('ca10b_EN_1.0p/ca10b_EN_1.0p.dta')
ass_12 = pd.read_stata('ca12c_EN_1.0p/ca12c_EN_1.0p.dta')
ass_14 = pd.read_stata('ca14d_2.0p_EN/ca14d_2.0p_EN.dta')
ass_16 = pd.read_stata('ca16e_EN_1.0p/ca16e_EN_1.0p.dta')
ass_18 = pd.read_stata('ca18f_EN_1.0p/ca18f_EN_1.0p.dta')
ass_20 = pd.read_stata('ca20g_EN_1.0p/ca20g_EN_1.0p.dta')
ass_22 = pd.read_stata('ca22h_EN_1.0p/ca22h_EN_1.0p.dta')

In [21]:
ass_all = [ass_08, ass_10, ass_12, ass_14, ass_16, ass_18, ass_20, ass_22]

ass_merged = ass_all[0]

for ass in ass_all[1:]:
    ass_merged = pd.merge(ass_merged, ass, on='nomem_encr', how='inner')

In [22]:
ass_merged.head()

,nomem_encr,nohouse_encr_x,ca08a_m,ca08a001,ca08a002,ca08a003,ca08a004,ca08a005,ca08a006,ca08a007,...,ca22h066,ca22h067,ca22h068,ca22h069,ca22h070,ca22h071,ca22h072,ca22h073,ca22h074,ca22h075
0,800057.0,580532.0,200806.0,yes,no,unmarried partner,yes,no,no,no,...,4,4,2,certainly not,2,22-09-2022,10:04:36,22-09-2022,10:06:55,139.0
1,800119.0,537783.0,200806.0,yes,no,married partner,no,no,no,no,...,3,4,3,3,3,13-09-2022,12:37:07,13-09-2022,12:37:39,32.0
2,800170.0,520571.0,200806.0,yes,yes,head of household*,yes,no,no,no,...,certainly not,certainly yes,3,certainly yes,certainly yes,13-09-2022,10:56:59,13-09-2022,10:59:22,143.0
3,800186.0,534976.0,200806.0,yes,no,married partner,yes,no,no,no,...,4,4,3,4,4,11-09-2022,18:50:15,11-09-2022,18:52:51,156.0
4,800201.0,529760.0,200806.0,yes,no,married partner,yes,no,no,no,...,2,certainly yes,2,4,4,05-09-2022,16:42:18,05-09-2022,16:44:56,158.0